<template>
  <div class="flex flex-col h-full justify-between">
    <h1 class="font-medium text-3xl">
      Lets begin the quiz!
      <span v-if="difficulty" class="text-sm">({{ difficulty }})</span>
    </h1>
    <Loading v-if="loading" />
    <div v-else-if="!error">
      <div
        class="flex flex-col gap-5 p-5 slide-in-right"
        v-for="(q, index) in questions"
        :key="q.question"
        v-if="currentQuestion === index"
      >
        <h2 class="text-lg" v-html="q.question" />
        <Button
          v-for="button in q.incorrect_answers.concat(q.correct_answer)"
          :key="button"
          :label="button"
          @click="setAnswer(button)"
        />
        <div class="text-xs text-red-500">{{ timer }}s remaining</div>
      </div>
    </div>
    <div class="flex flex-col gap-5 p-5 slide-in-right" v-else>
      <h2 class="text-md text-red-300">{{ error }}</h2>
      <Button label="Try again?" @click="reloadRouteFully" class="mt-auto" />
    </div>
    <div class="text-white text-xs text-indigo-500">
      <p>❓ Choose carefully!</p>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { quizModule } from "~/utils/store-accessor";
import Button from "~/components/Button.vue";
import Loading from "~/components/Loading.vue";
import Question from "~/types/Question";

export default Vue.extend({
  name: "QuizPage",
  components: { Button, Loading },
  head() {
    return {
      title: "Quiz",
    };
  },
  data() {
    return {
      currentQuestion: 0,
      timer: 10,
    };
  },
  computed: {
    difficulty(): String | null {
      return quizModule.difficulty;
    },
    questions(): Question[] {
      return quizModule.questions;
    },
    loading(): Boolean {
      return quizModule.loading;
    },
    error(): String | null {
      return quizModule.error;
    },
  },
  async mounted() {
    if (!this.difficulty) this.$router.push("/");
    if (!this.error) {
      await this.getQuestions();
      this.startTimer();
    }
  },

  methods: {
    async getQuestions() {
      await quizModule.fetchQuestions();
    },
    setAnswer(answer: string) {
      quizModule.setAnswers(answer);
      this.currentQuestion++;

      if (this.currentQuestion === this.questions.length) {
        this.$router.push("/results");
      } else {
        this.startTimer();
      }
    },
    startTimer() {
      if (this.error) return;

      const timerId = setInterval(() => {
        if (this.timer > 0) {
          this.timer--;
        } else {
          const currentQuestion = this.questions[this.currentQuestion];
          if (currentQuestion) {
            const incorrectAnswers = currentQuestion.incorrect_answers || [];
            const randomAnswer =
              incorrectAnswers[
                Math.floor(Math.random() * incorrectAnswers.length)
              ];
            this.setAnswer(randomAnswer);

            // Reset the timer for the next question
            this.timer = 10;
          }

          clearInterval(timerId);
        }
      }, 1000);
    },
    reloadRouteFully() {
      window.location.reload();
    },
  },
});
</script>

<style scoped>
.slide-in-right {
  -webkit-animation: slide-in-right 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: slide-in-right 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-11-20 13:22:12
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-right
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
    transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
    transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
</style>
